import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

async function main() {
  console.log("🌱 Seeding database...");

  // Create admin user
  const adminHash = await bcrypt.hash("admin123", 12);
  await prisma.user.upsert({
    where: { email: "pauledoux@protonmail.com" },
    update: {},
    create: {
      email: "pauledoux@protonmail.com",
      passwordHash: adminHash,
      role: "ADMIN",
    },
  });
  console.log("✅ Admin user created");

  // Create demo vendor
  const vendorHash = await bcrypt.hash("vendor123", 12);
  const vendorUser = await prisma.user.upsert({
    where: { email: "demo-vendor@borbi.app" },
    update: {},
    create: {
      email: "demo-vendor@borbi.app",
      passwordHash: vendorHash,
      role: "VENDOR",
      vendorProfile: {
        create: { businessName: "Boutique Modou", phone: "+221771234567" },
      },
    },
    include: { vendorProfile: true },
  });
  console.log("✅ Demo vendor created");

  // Create demo wholesaler
  const wholesalerHash = await bcrypt.hash("wholesaler123", 12);
  await prisma.user.upsert({
    where: { email: "demo-grossiste@borbi.app" },
    update: {},
    create: {
      email: "demo-grossiste@borbi.app",
      passwordHash: wholesalerHash,
      role: "WHOLESALER",
      wholesalerProfile: {
        create: { businessName: "Grossiste Dakar Distribution", phone: "+221779876543" },
      },
    },
  });
  console.log("✅ Demo wholesaler created");

  // Seed 500+ default products
  const products = [
    // ═══════════════════════════════════════════
    // BOULANGERIE (25 articles)
    // ═══════════════════════════════════════════
    { nameFr: "Baguette de pain", nameWolof: "Mburu", category: "boulangerie", unit: "unité", defaultPrice: 15000 },
    { nameFr: "Pain de mie", nameWolof: "Mburu bu weex", category: "boulangerie", unit: "unité", defaultPrice: 75000 },
    { nameFr: "Croissant", nameWolof: "Kruasaŋ", category: "boulangerie", unit: "unité", defaultPrice: 25000 },
    { nameFr: "Pain au chocolat", nameWolof: "Mburu sokolaa", category: "boulangerie", unit: "unité", defaultPrice: 30000 },
    { nameFr: "Baguette tradition", nameWolof: "Mburu tradisioŋ", category: "boulangerie", unit: "unité", defaultPrice: 20000 },
    { nameFr: "Pain complet", nameWolof: "Mburu bu mat", category: "boulangerie", unit: "unité", defaultPrice: 50000 },
    { nameFr: "Brioche", nameWolof: "Biriyoos", category: "boulangerie", unit: "unité", defaultPrice: 40000 },
    { nameFr: "Pain aux céréales", nameWolof: "Mburu sereal", category: "boulangerie", unit: "unité", defaultPrice: 60000 },
    { nameFr: "Petit pain rond", nameWolof: "Mburu bu ndaw", category: "boulangerie", unit: "unité", defaultPrice: 10000 },
    { nameFr: "Pain hamburger", nameWolof: "Mburu amburger", category: "boulangerie", unit: "paquet", defaultPrice: 100000 },
    { nameFr: "Pain hot-dog", nameWolof: "Mburu ot dog", category: "boulangerie", unit: "paquet", defaultPrice: 100000 },
    { nameFr: "Chausson aux pommes", nameWolof: "Sosoŋ pom", category: "boulangerie", unit: "unité", defaultPrice: 35000 },
    { nameFr: "Pain au lait", nameWolof: "Mburu meew", category: "boulangerie", unit: "unité", defaultPrice: 25000 },
    { nameFr: "Beignet", nameWolof: "Beeñe", category: "boulangerie", unit: "unité", defaultPrice: 5000 },
    { nameFr: "Fataya (chausson farci)", nameWolof: "Fataaya", category: "boulangerie", unit: "unité", defaultPrice: 10000 },
    { nameFr: "Pain au sésame", nameWolof: "Mburu sesam", category: "boulangerie", unit: "unité", defaultPrice: 20000 },
    { nameFr: "Croissant au beurre", nameWolof: "Kruasaŋ bër", category: "boulangerie", unit: "unité", defaultPrice: 35000 },
    { nameFr: "Gâteau au yaourt", nameWolof: "Gato yawurt", category: "boulangerie", unit: "unité", defaultPrice: 150000 },
    { nameFr: "Cake", nameWolof: "Keek", category: "boulangerie", unit: "unité", defaultPrice: 200000 },
    { nameFr: "Madeleine", nameWolof: "Madleen", category: "boulangerie", unit: "paquet", defaultPrice: 50000 },
    { nameFr: "Biscuit sec", nameWolof: "Biskwi", category: "boulangerie", unit: "paquet", defaultPrice: 30000 },
    { nameFr: "Pain pita", nameWolof: "Mburu pitaa", category: "boulangerie", unit: "paquet", defaultPrice: 75000 },
    { nameFr: "Pain de campagne", nameWolof: "Mburu dëkk bi", category: "boulangerie", unit: "unité", defaultPrice: 60000 },
    { nameFr: "Galette de mil", nameWolof: "Laax dugub", category: "boulangerie", unit: "unité", defaultPrice: 15000 },
    { nameFr: "Tarte aux fruits", nameWolof: "Tart meyy", category: "boulangerie", unit: "unité", defaultPrice: 250000 },

    // ═══════════════════════════════════════════
    // FRAIS & PROTÉINES (45 articles)
    // ═══════════════════════════════════════════
    { nameFr: "Poulet entier", nameWolof: "Ginaar", category: "frais", unit: "kg", defaultPrice: 250000 },
    { nameFr: "Cuisse de poulet", nameWolof: "Tànk ginaar", category: "frais", unit: "kg", defaultPrice: 300000 },
    { nameFr: "Aile de poulet", nameWolof: "Loxo ginaar", category: "frais", unit: "kg", defaultPrice: 280000 },
    { nameFr: "Viande de bœuf", nameWolof: "Yàpp nag", category: "frais", unit: "kg", defaultPrice: 450000 },
    { nameFr: "Viande de mouton", nameWolof: "Yàpp xar", category: "frais", unit: "kg", defaultPrice: 500000 },
    { nameFr: "Viande de chèvre", nameWolof: "Yàpp bëy", category: "frais", unit: "kg", defaultPrice: 480000 },
    { nameFr: "Foie de bœuf", nameWolof: "Res nag", category: "frais", unit: "kg", defaultPrice: 350000 },
    { nameFr: "Tripes", nameWolof: "Bët", category: "frais", unit: "kg", defaultPrice: 200000 },
    { nameFr: "Poisson Thiof", nameWolof: "Cof", category: "frais", unit: "kg", defaultPrice: 500000 },
    { nameFr: "Poisson Capitaine", nameWolof: "Sëgg", category: "frais", unit: "kg", defaultPrice: 400000 },
    { nameFr: "Poisson Chinchard", nameWolof: "Yaboy", category: "frais", unit: "kg", defaultPrice: 150000 },
    { nameFr: "Crevettes", nameWolof: "Sippax", category: "frais", unit: "kg", defaultPrice: 600000 },
    { nameFr: "Poisson fumé", nameWolof: "Jën bu tàcc", category: "frais", unit: "kg", defaultPrice: 350000 },
    { nameFr: "Poisson séché (guedj)", nameWolof: "Guëj", category: "frais", unit: "kg", defaultPrice: 400000 },
    { nameFr: "Sardine fraîche", nameWolof: "Sardin", category: "frais", unit: "kg", defaultPrice: 120000 },
    { nameFr: "Lait frais", nameWolof: "Meew", category: "frais", unit: "litre", defaultPrice: 80000 },
    { nameFr: "Lait caillé (raw)", nameWolof: "Soow", category: "frais", unit: "litre", defaultPrice: 60000 },
    { nameFr: "Yaourt nature", nameWolof: "Yawurt", category: "frais", unit: "unité", defaultPrice: 25000 },
    { nameFr: "Yaourt sucré", nameWolof: "Yawurt sukër", category: "frais", unit: "unité", defaultPrice: 30000 },
    { nameFr: "Fromage fondu", nameWolof: "Fromaas", category: "frais", unit: "boîte", defaultPrice: 75000 },
    { nameFr: "Beurre", nameWolof: "Bër", category: "frais", unit: "plaquette", defaultPrice: 100000 },
    { nameFr: "Margarine", nameWolof: "Margariin", category: "frais", unit: "pot", defaultPrice: 60000 },
    { nameFr: "Œufs (plateau 30)", nameWolof: "Nen (plato)", category: "frais", unit: "plateau", defaultPrice: 250000 },
    { nameFr: "Œuf (unité)", nameWolof: "Nen", category: "frais", unit: "unité", defaultPrice: 10000 },
    { nameFr: "Lait en poudre Nido 400g", nameWolof: "Meew Nido", category: "frais", unit: "boîte", defaultPrice: 300000 },
    { nameFr: "Lait en poudre Nido 900g", nameWolof: "Meew Nido bu mag", category: "frais", unit: "boîte", defaultPrice: 550000 },
    { nameFr: "Lait concentré sucré", nameWolof: "Meew konsantre", category: "frais", unit: "boîte", defaultPrice: 50000 },
    { nameFr: "Lait concentré non sucré", nameWolof: "Meew bu doodul", category: "frais", unit: "boîte", defaultPrice: 45000 },
    { nameFr: "Crème fraîche", nameWolof: "Krem", category: "frais", unit: "pot", defaultPrice: 80000 },
    { nameFr: "Saucisson", nameWolof: "Sosisoŋ", category: "frais", unit: "unité", defaultPrice: 150000 },
    { nameFr: "Merguez", nameWolof: "Mergez", category: "frais", unit: "kg", defaultPrice: 350000 },
    { nameFr: "Poulet fumé", nameWolof: "Ginaar bu tàcc", category: "frais", unit: "unité", defaultPrice: 400000 },
    { nameFr: "Poisson Dorade", nameWolof: "Dorad", category: "frais", unit: "kg", defaultPrice: 350000 },
    { nameFr: "Poisson Barracuda", nameWolof: "Sëdd", category: "frais", unit: "kg", defaultPrice: 300000 },
    { nameFr: "Calamar", nameWolof: "Kalmar", category: "frais", unit: "kg", defaultPrice: 450000 },
    { nameFr: "Poulpe", nameWolof: "Yàmb", category: "frais", unit: "kg", defaultPrice: 500000 },
    { nameFr: "Fromage râpé", nameWolof: "Fromaas raappe", category: "frais", unit: "sachet", defaultPrice: 100000 },
    { nameFr: "Yaourt à boire", nameWolof: "Yawurt naan", category: "frais", unit: "bouteille", defaultPrice: 35000 },
    { nameFr: "Lait UHT 1L", nameWolof: "Meew UHT", category: "frais", unit: "litre", defaultPrice: 90000 },
    { nameFr: "Corned beef", nameWolof: "Korned biif", category: "frais", unit: "boîte", defaultPrice: 80000 },
    { nameFr: "Pâté", nameWolof: "Paate", category: "frais", unit: "boîte", defaultPrice: 60000 },
    { nameFr: "Saucisse de Strasbourg", nameWolof: "Soosis", category: "frais", unit: "paquet", defaultPrice: 120000 },
    { nameFr: "Filet de poisson", nameWolof: "File jën", category: "frais", unit: "kg", defaultPrice: 400000 },
    { nameFr: "Côtelette de mouton", nameWolof: "Kot xar", category: "frais", unit: "kg", defaultPrice: 550000 },
    { nameFr: "Steak haché", nameWolof: "Steek", category: "frais", unit: "kg", defaultPrice: 400000 },

    // ═══════════════════════════════════════════
    // FRUITS & LÉGUMES (40 articles)
    // ═══════════════════════════════════════════
    { nameFr: "Oignon local", nameWolof: "Soble", category: "fruitsLegumes", unit: "kg", defaultPrice: 40000 },
    { nameFr: "Tomate fraîche", nameWolof: "Tamaate", category: "fruitsLegumes", unit: "kg", defaultPrice: 50000 },
    { nameFr: "Pomme de terre", nameWolof: "Pombiteer", category: "fruitsLegumes", unit: "kg", defaultPrice: 35000 },
    { nameFr: "Carotte", nameWolof: "Karot", category: "fruitsLegumes", unit: "kg", defaultPrice: 40000 },
    { nameFr: "Chou", nameWolof: "Suu", category: "fruitsLegumes", unit: "unité", defaultPrice: 30000 },
    { nameFr: "Aubergine", nameWolof: "Bataŋs", category: "fruitsLegumes", unit: "kg", defaultPrice: 35000 },
    { nameFr: "Piment", nameWolof: "Kani", category: "fruitsLegumes", unit: "kg", defaultPrice: 60000 },
    { nameFr: "Poivron vert", nameWolof: "Pwavroŋ wert", category: "fruitsLegumes", unit: "kg", defaultPrice: 50000 },
    { nameFr: "Ail", nameWolof: "Laay", category: "fruitsLegumes", unit: "kg", defaultPrice: 100000 },
    { nameFr: "Persil", nameWolof: "Persi", category: "fruitsLegumes", unit: "botte", defaultPrice: 10000 },
    { nameFr: "Menthe", nameWolof: "Naanaa", category: "fruitsLegumes", unit: "botte", defaultPrice: 10000 },
    { nameFr: "Salade laitue", nameWolof: "Salat", category: "fruitsLegumes", unit: "unité", defaultPrice: 20000 },
    { nameFr: "Concombre", nameWolof: "Koŋkomb", category: "fruitsLegumes", unit: "unité", defaultPrice: 15000 },
    { nameFr: "Courgette", nameWolof: "Kurset", category: "fruitsLegumes", unit: "kg", defaultPrice: 40000 },
    { nameFr: "Navet", nameWolof: "Nawe", category: "fruitsLegumes", unit: "kg", defaultPrice: 30000 },
    { nameFr: "Gombo (okra)", nameWolof: "Kànja", category: "fruitsLegumes", unit: "kg", defaultPrice: 50000 },
    { nameFr: "Manioc", nameWolof: "Ñambi", category: "fruitsLegumes", unit: "kg", defaultPrice: 25000 },
    { nameFr: "Patate douce", nameWolof: "Pataas", category: "fruitsLegumes", unit: "kg", defaultPrice: 30000 },
    { nameFr: "Igname", nameWolof: "Ñaam", category: "fruitsLegumes", unit: "kg", defaultPrice: 45000 },
    { nameFr: "Bissap (oseille)", nameWolof: "Bisaab", category: "fruitsLegumes", unit: "kg", defaultPrice: 60000 },
    { nameFr: "Banane", nameWolof: "Banaana", category: "fruitsLegumes", unit: "kg", defaultPrice: 40000 },
    { nameFr: "Mangue", nameWolof: "Mango", category: "fruitsLegumes", unit: "kg", defaultPrice: 50000 },
    { nameFr: "Orange", nameWolof: "Oraas", category: "fruitsLegumes", unit: "kg", defaultPrice: 40000 },
    { nameFr: "Mandarine", nameWolof: "Maŋdarin", category: "fruitsLegumes", unit: "kg", defaultPrice: 45000 },
    { nameFr: "Citron", nameWolof: "Limoŋ", category: "fruitsLegumes", unit: "kg", defaultPrice: 30000 },
    { nameFr: "Papaye", nameWolof: "Papaay", category: "fruitsLegumes", unit: "unité", defaultPrice: 50000 },
    { nameFr: "Pastèque", nameWolof: "Xaal", category: "fruitsLegumes", unit: "unité", defaultPrice: 100000 },
    { nameFr: "Melon", nameWolof: "Meloŋ", category: "fruitsLegumes", unit: "unité", defaultPrice: 80000 },
    { nameFr: "Ananas", nameWolof: "Ananas", category: "fruitsLegumes", unit: "unité", defaultPrice: 60000 },
    { nameFr: "Noix de coco", nameWolof: "Koko", category: "fruitsLegumes", unit: "unité", defaultPrice: 25000 },
    { nameFr: "Avocat", nameWolof: "Awokaa", category: "fruitsLegumes", unit: "unité", defaultPrice: 30000 },
    { nameFr: "Pomme importée", nameWolof: "Pom", category: "fruitsLegumes", unit: "kg", defaultPrice: 80000 },
    { nameFr: "Raisin", nameWolof: "Reseŋ", category: "fruitsLegumes", unit: "kg", defaultPrice: 120000 },
    { nameFr: "Ditakh", nameWolof: "Ditax", category: "fruitsLegumes", unit: "kg", defaultPrice: 50000 },
    { nameFr: "Madd", nameWolof: "Madd", category: "fruitsLegumes", unit: "kg", defaultPrice: 60000 },
    { nameFr: "Tamarin (dakhar)", nameWolof: "Daxar", category: "fruitsLegumes", unit: "kg", defaultPrice: 40000 },
    { nameFr: "Gingembre", nameWolof: "Jinjeer", category: "fruitsLegumes", unit: "kg", defaultPrice: 60000 },
    { nameFr: "Citronnelle", nameWolof: "Tiim", category: "fruitsLegumes", unit: "botte", defaultPrice: 10000 },
    { nameFr: "Haricot vert", nameWolof: "Ariko wert", category: "fruitsLegumes", unit: "kg", defaultPrice: 50000 },
    { nameFr: "Betterave", nameWolof: "Betraw", category: "fruitsLegumes", unit: "kg", defaultPrice: 40000 },

    // ═══════════════════════════════════════════
    // ÉPICERIE & CONSERVES (65 articles)
    // ═══════════════════════════════════════════
    { nameFr: "Riz brisé local 25kg", nameWolof: "Ceeb lokal", category: "epicerie", unit: "sac", defaultPrice: 1200000 },
    { nameFr: "Riz brisé local 5kg", nameWolof: "Ceeb lokal", category: "epicerie", unit: "sac", defaultPrice: 280000 },
    { nameFr: "Riz parfumé 5kg", nameWolof: "Ceeb parfëme", category: "epicerie", unit: "sac", defaultPrice: 350000 },
    { nameFr: "Riz parfumé 25kg", nameWolof: "Ceeb parfëme", category: "epicerie", unit: "sac", defaultPrice: 1500000 },
    { nameFr: "Mil (souna)", nameWolof: "Suuna", category: "epicerie", unit: "kg", defaultPrice: 40000 },
    { nameFr: "Maïs en grains", nameWolof: "Mbahal", category: "epicerie", unit: "kg", defaultPrice: 30000 },
    { nameFr: "Farine de blé 1kg", nameWolof: "Farin", category: "epicerie", unit: "kg", defaultPrice: 40000 },
    { nameFr: "Farine de mil", nameWolof: "Farin suuna", category: "epicerie", unit: "kg", defaultPrice: 50000 },
    { nameFr: "Semoule de blé 1kg", nameWolof: "Sëmuul", category: "epicerie", unit: "kg", defaultPrice: 45000 },
    { nameFr: "Couscous 1kg", nameWolof: "Kuskus", category: "epicerie", unit: "kg", defaultPrice: 50000 },
    { nameFr: "Pâtes spaghetti 500g", nameWolof: "Makaarooni", category: "epicerie", unit: "paquet", defaultPrice: 35000 },
    { nameFr: "Pâtes macaroni 500g", nameWolof: "Makaarooni", category: "epicerie", unit: "paquet", defaultPrice: 35000 },
    { nameFr: "Vermicelle 500g", nameWolof: "Wërmisel", category: "epicerie", unit: "paquet", defaultPrice: 30000 },
    { nameFr: "Huile d'arachide 1L", nameWolof: "Diw gerte", category: "epicerie", unit: "litre", defaultPrice: 100000 },
    { nameFr: "Huile d'arachide 5L", nameWolof: "Diw gerte", category: "epicerie", unit: "bidon", defaultPrice: 450000 },
    { nameFr: "Huile de palme 1L", nameWolof: "Diw tiir", category: "epicerie", unit: "litre", defaultPrice: 80000 },
    { nameFr: "Huile végétale 1L", nameWolof: "Diw wegetaal", category: "epicerie", unit: "litre", defaultPrice: 70000 },
    { nameFr: "Huile d'olive 500ml", nameWolof: "Diw oliw", category: "epicerie", unit: "bouteille", defaultPrice: 250000 },
    { nameFr: "Sucre en poudre 1kg", nameWolof: "Sukër", category: "epicerie", unit: "kg", defaultPrice: 60000 },
    { nameFr: "Sucre en morceaux 1kg", nameWolof: "Sukër tàmb", category: "epicerie", unit: "kg", defaultPrice: 70000 },
    { nameFr: "Sel fin 1kg", nameWolof: "Xorom", category: "epicerie", unit: "kg", defaultPrice: 15000 },
    { nameFr: "Sel gros 1kg", nameWolof: "Xorom bu mag", category: "epicerie", unit: "kg", defaultPrice: 10000 },
    { nameFr: "Poivre noir moulu", nameWolof: "Puwawru", category: "epicerie", unit: "sachet", defaultPrice: 15000 },
    { nameFr: "Bouillon Jumbo (carton)", nameWolof: "Jumbo", category: "epicerie", unit: "carton", defaultPrice: 200000 },
    { nameFr: "Bouillon Maggi (sachet)", nameWolof: "Magi", category: "epicerie", unit: "sachet", defaultPrice: 2500 },
    { nameFr: "Concentré de tomate 70g", nameWolof: "Tamaate konsantre", category: "epicerie", unit: "boîte", defaultPrice: 15000 },
    { nameFr: "Concentré de tomate 400g", nameWolof: "Tamaate konsantre", category: "epicerie", unit: "boîte", defaultPrice: 60000 },
    { nameFr: "Double concentré de tomate 800g", nameWolof: "Tamaate dubl", category: "epicerie", unit: "boîte", defaultPrice: 100000 },
    { nameFr: "Sardines en conserve", nameWolof: "Sardin bwaat", category: "epicerie", unit: "boîte", defaultPrice: 40000 },
    { nameFr: "Thon en conserve", nameWolof: "Toŋ bwaat", category: "epicerie", unit: "boîte", defaultPrice: 60000 },
    { nameFr: "Petit pois en conserve", nameWolof: "Peti pwa bwaat", category: "epicerie", unit: "boîte", defaultPrice: 45000 },
    { nameFr: "Haricots rouges en conserve", nameWolof: "Ñebbe ruuj bwaat", category: "epicerie", unit: "boîte", defaultPrice: 45000 },
    { nameFr: "Maïs en conserve", nameWolof: "Mbahal bwaat", category: "epicerie", unit: "boîte", defaultPrice: 50000 },
    { nameFr: "Confiture 370g", nameWolof: "Koŋfitir", category: "epicerie", unit: "pot", defaultPrice: 80000 },
    { nameFr: "Miel 500g", nameWolof: "Lëm", category: "epicerie", unit: "pot", defaultPrice: 200000 },
    { nameFr: "Chocolat en poudre 400g", nameWolof: "Sokolaa pudër", category: "epicerie", unit: "boîte", defaultPrice: 150000 },
    { nameFr: "Café soluble 200g", nameWolof: "Kafee", category: "epicerie", unit: "pot", defaultPrice: 200000 },
    { nameFr: "Café Touba 250g", nameWolof: "Kafee Tuuba", category: "epicerie", unit: "paquet", defaultPrice: 75000 },
    { nameFr: "Thé vert (boîte)", nameWolof: "Attaaya", category: "epicerie", unit: "boîte", defaultPrice: 50000 },
    { nameFr: "Kinkeliba (sachet)", nameWolof: "Kinkeliba", category: "epicerie", unit: "sachet", defaultPrice: 15000 },
    { nameFr: "Arachide décortiquée 1kg", nameWolof: "Gerte", category: "epicerie", unit: "kg", defaultPrice: 60000 },
    { nameFr: "Niébé (haricot blanc) 1kg", nameWolof: "Ñebbe", category: "epicerie", unit: "kg", defaultPrice: 50000 },
    { nameFr: "Lentilles 500g", nameWolof: "Laŋtiy", category: "epicerie", unit: "paquet", defaultPrice: 40000 },
    { nameFr: "Pâte d'arachide 500g", nameWolof: "Tikëre", category: "epicerie", unit: "pot", defaultPrice: 60000 },
    { nameFr: "Vinaigre 1L", nameWolof: "Winegër", category: "epicerie", unit: "bouteille", defaultPrice: 30000 },
    { nameFr: "Moutarde 200g", nameWolof: "Mutard", category: "epicerie", unit: "pot", defaultPrice: 35000 },
    { nameFr: "Mayonnaise 500g", nameWolof: "Mayonees", category: "epicerie", unit: "pot", defaultPrice: 80000 },
    { nameFr: "Sauce soja 250ml", nameWolof: "Sos sooya", category: "epicerie", unit: "bouteille", defaultPrice: 50000 },
    { nameFr: "Pâtes lasagnes 500g", nameWolof: "Lazaañ", category: "epicerie", unit: "paquet", defaultPrice: 60000 },
    { nameFr: "Levure boulangère", nameWolof: "Lëwir", category: "epicerie", unit: "sachet", defaultPrice: 5000 },
    { nameFr: "Bicarbonate de soude", nameWolof: "Bikarbonaat", category: "epicerie", unit: "sachet", defaultPrice: 10000 },
    { nameFr: "Fécule de maïs (Maïzena)", nameWolof: "Meseena", category: "epicerie", unit: "paquet", defaultPrice: 30000 },
    { nameFr: "Noix de cajou 250g", nameWolof: "Darkasu", category: "epicerie", unit: "sachet", defaultPrice: 100000 },
    { nameFr: "Dattes 500g", nameWolof: "Tàmàr", category: "epicerie", unit: "paquet", defaultPrice: 80000 },
    { nameFr: "Sésame 250g", nameWolof: "Gérgelin", category: "epicerie", unit: "sachet", defaultPrice: 40000 },
    { nameFr: "Soumbala (nététu)", nameWolof: "Netettu", category: "epicerie", unit: "sachet", defaultPrice: 25000 },
    { nameFr: "Poudre de baobab (bouye)", nameWolof: "Buy", category: "epicerie", unit: "sachet", defaultPrice: 30000 },
    { nameFr: "Fonio 1kg", nameWolof: "Foñoo", category: "epicerie", unit: "kg", defaultPrice: 80000 },
    { nameFr: "Sauce tomate 400g", nameWolof: "Sos tamaate", category: "epicerie", unit: "boîte", defaultPrice: 50000 },
    { nameFr: "Olives vertes 200g", nameWolof: "Oliw", category: "epicerie", unit: "pot", defaultPrice: 60000 },
    { nameFr: "Cornichons 370g", nameWolof: "Kornisoon", category: "epicerie", unit: "pot", defaultPrice: 50000 },
    { nameFr: "Chips 100g", nameWolof: "Sips", category: "epicerie", unit: "paquet", defaultPrice: 30000 },
    { nameFr: "Biscuits LU 200g", nameWolof: "Biskwi", category: "epicerie", unit: "paquet", defaultPrice: 40000 },
    { nameFr: "Bonbons (sachet)", nameWolof: "Bonboŋ", category: "epicerie", unit: "sachet", defaultPrice: 15000 },
    { nameFr: "Chewing-gum (boîte)", nameWolof: "Suiŋ gom", category: "epicerie", unit: "boîte", defaultPrice: 20000 },

    // ═══════════════════════════════════════════
    // BOISSONS (55 articles)
    // ═══════════════════════════════════════════
    { nameFr: "Eau minérale 1.5L", nameWolof: "Ndox mineraal", category: "boissons", unit: "bouteille", defaultPrice: 30000 },
    { nameFr: "Eau minérale 0.5L", nameWolof: "Ndox mineraal", category: "boissons", unit: "bouteille", defaultPrice: 15000 },
    { nameFr: "Eau en sachet (vendeur)", nameWolof: "Ndox sase", category: "boissons", unit: "paquet", defaultPrice: 5000 },
    { nameFr: "Coca-Cola 1.5L", nameWolof: "Koka", category: "boissons", unit: "bouteille", defaultPrice: 60000 },
    { nameFr: "Coca-Cola 33cl", nameWolof: "Koka", category: "boissons", unit: "bouteille", defaultPrice: 30000 },
    { nameFr: "Fanta Orange 1.5L", nameWolof: "Faŋta", category: "boissons", unit: "bouteille", defaultPrice: 60000 },
    { nameFr: "Fanta Orange 33cl", nameWolof: "Faŋta", category: "boissons", unit: "bouteille", defaultPrice: 30000 },
    { nameFr: "Sprite 1.5L", nameWolof: "Sprayt", category: "boissons", unit: "bouteille", defaultPrice: 60000 },
    { nameFr: "Sprite 33cl", nameWolof: "Sprayt", category: "boissons", unit: "bouteille", defaultPrice: 30000 },
    { nameFr: "Schweppes Tonic 33cl", nameWolof: "Sweeps", category: "boissons", unit: "bouteille", defaultPrice: 35000 },
    { nameFr: "Flag Bière 66cl", nameWolof: "Flag", category: "boissons", unit: "bouteille", defaultPrice: 70000 },
    { nameFr: "Gazelle Bière 66cl", nameWolof: "Gasel", category: "boissons", unit: "bouteille", defaultPrice: 70000 },
    { nameFr: "Malta Guinness 33cl", nameWolof: "Malta", category: "boissons", unit: "bouteille", defaultPrice: 40000 },
    { nameFr: "Jus de bissap 1L", nameWolof: "Ndox bisaab", category: "boissons", unit: "bouteille", defaultPrice: 50000 },
    { nameFr: "Jus de gingembre 1L", nameWolof: "Ndox jinjeer", category: "boissons", unit: "bouteille", defaultPrice: 50000 },
    { nameFr: "Jus de bouye 1L", nameWolof: "Ndox buy", category: "boissons", unit: "bouteille", defaultPrice: 50000 },
    { nameFr: "Jus de tamarin 1L", nameWolof: "Ndox daxar", category: "boissons", unit: "bouteille", defaultPrice: 50000 },
    { nameFr: "Jus de ditakh 1L", nameWolof: "Ndox ditax", category: "boissons", unit: "bouteille", defaultPrice: 60000 },
    { nameFr: "Jus d'orange industriel 1L", nameWolof: "Ji oraas", category: "boissons", unit: "brique", defaultPrice: 60000 },
    { nameFr: "Jus de pomme 1L", nameWolof: "Ji pom", category: "boissons", unit: "brique", defaultPrice: 60000 },
    { nameFr: "Jus de mangue 1L", nameWolof: "Ji mango", category: "boissons", unit: "brique", defaultPrice: 60000 },
    { nameFr: "Red Bull 25cl", nameWolof: "Red Bull", category: "boissons", unit: "canette", defaultPrice: 80000 },
    { nameFr: "Monster Energy 50cl", nameWolof: "Monster", category: "boissons", unit: "canette", defaultPrice: 90000 },
    { nameFr: "Café filtre torréfié 250g", nameWolof: "Kafee filtr", category: "boissons", unit: "paquet", defaultPrice: 100000 },
    { nameFr: "Thé Lipton (boîte 25)", nameWolof: "Tee Liptoŋ", category: "boissons", unit: "boîte", defaultPrice: 60000 },
    { nameFr: "Nescafé 3-en-1 (10 sachets)", nameWolof: "Neskafe", category: "boissons", unit: "boîte", defaultPrice: 80000 },
    { nameFr: "Sirop de menthe 1L", nameWolof: "Siro naanaa", category: "boissons", unit: "bouteille", defaultPrice: 100000 },
    { nameFr: "Sirop de grenadine 1L", nameWolof: "Siro grënadin", category: "boissons", unit: "bouteille", defaultPrice: 100000 },
    { nameFr: "Eau de Javel 1L", nameWolof: "Jaavel", category: "boissons", unit: "bouteille", defaultPrice: 30000 },
    { nameFr: "Pepsi 1.5L", nameWolof: "Pepsi", category: "boissons", unit: "bouteille", defaultPrice: 55000 },
    { nameFr: "7Up 1.5L", nameWolof: "Sëwën Op", category: "boissons", unit: "bouteille", defaultPrice: 55000 },
    { nameFr: "Mirinda 1.5L", nameWolof: "Mirinda", category: "boissons", unit: "bouteille", defaultPrice: 55000 },
    { nameFr: "Eau gazeuse 1L", nameWolof: "Ndox gaaz", category: "boissons", unit: "bouteille", defaultPrice: 40000 },
    { nameFr: "Lait de soja 1L", nameWolof: "Meew sooya", category: "boissons", unit: "bouteille", defaultPrice: 80000 },
    { nameFr: "Vin rouge (bouteille)", nameWolof: "Biñ ruuj", category: "boissons", unit: "bouteille", defaultPrice: 300000 },
    { nameFr: "Vin blanc (bouteille)", nameWolof: "Biñ blaŋ", category: "boissons", unit: "bouteille", defaultPrice: 300000 },
    { nameFr: "Whisky (bouteille)", nameWolof: "Wiski", category: "boissons", unit: "bouteille", defaultPrice: 800000 },
    { nameFr: "Rhum 1L", nameWolof: "Rom", category: "boissons", unit: "bouteille", defaultPrice: 500000 },
    { nameFr: "Vodka 1L", nameWolof: "Wotka", category: "boissons", unit: "bouteille", defaultPrice: 600000 },
    { nameFr: "Champagne", nameWolof: "Saaŋpaañ", category: "boissons", unit: "bouteille", defaultPrice: 1000000 },
    { nameFr: "Coca-Cola canette 33cl", nameWolof: "Koka kanëtt", category: "boissons", unit: "canette", defaultPrice: 35000 },
    { nameFr: "Fanta canette 33cl", nameWolof: "Faŋta kanëtt", category: "boissons", unit: "canette", defaultPrice: 35000 },
    { nameFr: "Eau plate pack 6x1.5L", nameWolof: "Ndox pak", category: "boissons", unit: "pack", defaultPrice: 150000 },
    { nameFr: "Boisson énergétique locale", nameWolof: "Ndox doole", category: "boissons", unit: "bouteille", defaultPrice: 30000 },
    { nameFr: "Jus multi-fruits 1L", nameWolof: "Ji meyy", category: "boissons", unit: "brique", defaultPrice: 55000 },

    // ═══════════════════════════════════════════
    // HYGIÈNE & BAZAR (45 articles)
    // ═══════════════════════════════════════════
    { nameFr: "Savon de Marseille 400g", nameWolof: "Sawoŋ Marsëy", category: "hygiene", unit: "unité", defaultPrice: 30000 },
    { nameFr: "Savon Palmolive", nameWolof: "Sawoŋ Palmoliv", category: "hygiene", unit: "unité", defaultPrice: 25000 },
    { nameFr: "Savon Protex", nameWolof: "Sawoŋ Proteks", category: "hygiene", unit: "unité", defaultPrice: 30000 },
    { nameFr: "Savon noir (sabou gongo)", nameWolof: "Sawoŋ bu ñuul", category: "hygiene", unit: "unité", defaultPrice: 20000 },
    { nameFr: "Gel douche 250ml", nameWolof: "Jel duus", category: "hygiene", unit: "bouteille", defaultPrice: 100000 },
    { nameFr: "Shampoing 250ml", nameWolof: "Saaŋpuwaŋ", category: "hygiene", unit: "bouteille", defaultPrice: 100000 },
    { nameFr: "Dentifrice Colgate", nameWolof: "Daaŋtifris", category: "hygiene", unit: "tube", defaultPrice: 40000 },
    { nameFr: "Brosse à dents", nameWolof: "Bros bëñ", category: "hygiene", unit: "unité", defaultPrice: 15000 },
    { nameFr: "Déodorant stick", nameWolof: "Deodoraan", category: "hygiene", unit: "unité", defaultPrice: 60000 },
    { nameFr: "Déodorant spray", nameWolof: "Deodoraan spree", category: "hygiene", unit: "unité", defaultPrice: 80000 },
    { nameFr: "Parfum (eau de toilette)", nameWolof: "Parfëm", category: "hygiene", unit: "bouteille", defaultPrice: 200000 },
    { nameFr: "Crème de corps 200ml", nameWolof: "Krem yaram", category: "hygiene", unit: "pot", defaultPrice: 60000 },
    { nameFr: "Huile corporelle 100ml", nameWolof: "Diw yaram", category: "hygiene", unit: "bouteille", defaultPrice: 50000 },
    { nameFr: "Lessive en poudre 1kg", nameWolof: "Lesiiw", category: "hygiene", unit: "paquet", defaultPrice: 60000 },
    { nameFr: "Lessive en poudre 5kg", nameWolof: "Lesiiw bu mag", category: "hygiene", unit: "sac", defaultPrice: 250000 },
    { nameFr: "Savon en poudre OMO 500g", nameWolof: "OMO", category: "hygiene", unit: "paquet", defaultPrice: 40000 },
    { nameFr: "Liquide vaisselle 500ml", nameWolof: "Wàsël", category: "hygiene", unit: "bouteille", defaultPrice: 40000 },
    { nameFr: "Éponge à récurer", nameWolof: "Epoŋj", category: "hygiene", unit: "unité", defaultPrice: 10000 },
    { nameFr: "Papier toilette (4 rouleaux)", nameWolof: "Papye twalet", category: "hygiene", unit: "paquet", defaultPrice: 50000 },
    { nameFr: "Mouchoirs en papier", nameWolof: "Muswaar papye", category: "hygiene", unit: "paquet", defaultPrice: 15000 },
    { nameFr: "Serviettes hygiéniques (10)", nameWolof: "Serwiyeet", category: "hygiene", unit: "paquet", defaultPrice: 40000 },
    { nameFr: "Couches bébé (20 pièces)", nameWolof: "Kuus", category: "hygiene", unit: "paquet", defaultPrice: 300000 },
    { nameFr: "Lingettes bébé (60)", nameWolof: "Liŋjeet", category: "hygiene", unit: "paquet", defaultPrice: 80000 },
    { nameFr: "Insecticide spray", nameWolof: "Sëf bëcëk", category: "hygiene", unit: "bouteille", defaultPrice: 80000 },
    { nameFr: "Spirale anti-moustique", nameWolof: "Espiral", category: "hygiene", unit: "boîte", defaultPrice: 30000 },
    { nameFr: "Bougie", nameWolof: "Bugi", category: "hygiene", unit: "unité", defaultPrice: 10000 },
    { nameFr: "Allumettes (boîte)", nameWolof: "Alumeet", category: "hygiene", unit: "boîte", defaultPrice: 5000 },
    { nameFr: "Briquet", nameWolof: "Brike", category: "hygiene", unit: "unité", defaultPrice: 10000 },
    { nameFr: "Piles AA (4 pièces)", nameWolof: "Piil", category: "hygiene", unit: "paquet", defaultPrice: 30000 },
    { nameFr: "Piles AAA (4 pièces)", nameWolof: "Piil ndaw", category: "hygiene", unit: "paquet", defaultPrice: 30000 },
    { nameFr: "Ampoule LED", nameWolof: "Aŋpul", category: "hygiene", unit: "unité", defaultPrice: 40000 },
    { nameFr: "Scotch/ruban adhésif", nameWolof: "Skoos", category: "hygiene", unit: "rouleau", defaultPrice: 15000 },
    { nameFr: "Colle forte", nameWolof: "Kol", category: "hygiene", unit: "tube", defaultPrice: 15000 },
    { nameFr: "Sac poubelle (10 pièces)", nameWolof: "Sak saletee", category: "hygiene", unit: "paquet", defaultPrice: 20000 },
    { nameFr: "Balai", nameWolof: "Bale", category: "hygiene", unit: "unité", defaultPrice: 30000 },
    { nameFr: "Serpillière", nameWolof: "Serpiyeer", category: "hygiene", unit: "unité", defaultPrice: 20000 },
    { nameFr: "Seau 10L", nameWolof: "Soo", category: "hygiene", unit: "unité", defaultPrice: 40000 },
    { nameFr: "Bassine en plastique", nameWolof: "Basin", category: "hygiene", unit: "unité", defaultPrice: 50000 },
    { nameFr: "Cintres (lot de 10)", nameWolof: "Seŋtr", category: "hygiene", unit: "lot", defaultPrice: 25000 },
    { nameFr: "Cire à chaussure", nameWolof: "Sir daal", category: "hygiene", unit: "boîte", defaultPrice: 15000 },
    { nameFr: "Rasoir jetable (5)", nameWolof: "Rasuwaar", category: "hygiene", unit: "paquet", defaultPrice: 20000 },
    { nameFr: "Coton-tige (100)", nameWolof: "Kotoŋ tiig", category: "hygiene", unit: "boîte", defaultPrice: 15000 },
    { nameFr: "Vaseline 100ml", nameWolof: "Waslin", category: "hygiene", unit: "pot", defaultPrice: 20000 },
    { nameFr: "Henné", nameWolof: "Xeesal", category: "hygiene", unit: "sachet", defaultPrice: 15000 },
    { nameFr: "Huile de coco 100ml", nameWolof: "Diw koko", category: "hygiene", unit: "bouteille", defaultPrice: 40000 },

    // ═══════════════════════════════════════════
    // ÉNERGIE & TECH (35 articles)
    // ═══════════════════════════════════════════
    { nameFr: "Bonbonne de gaz 6kg", nameWolof: "Gaas 6", category: "energieTech", unit: "unité", defaultPrice: 350000 },
    { nameFr: "Bonbonne de gaz 12kg", nameWolof: "Gaas 12", category: "energieTech", unit: "unité", defaultPrice: 600000 },
    { nameFr: "Bonbonne de gaz 2.7kg", nameWolof: "Gaas ndaw", category: "energieTech", unit: "unité", defaultPrice: 180000 },
    { nameFr: "Charbon de bois 25kg", nameWolof: "Safara bant", category: "energieTech", unit: "sac", defaultPrice: 300000 },
    { nameFr: "Pétrole lampant 1L", nameWolof: "Petrol", category: "energieTech", unit: "litre", defaultPrice: 50000 },
    { nameFr: "Chargeur téléphone USB", nameWolof: "Saarzër", category: "energieTech", unit: "unité", defaultPrice: 50000 },
    { nameFr: "Chargeur USB-C rapide", nameWolof: "Saarzër USB-C", category: "energieTech", unit: "unité", defaultPrice: 80000 },
    { nameFr: "Câble USB micro", nameWolof: "Kaabl USB", category: "energieTech", unit: "unité", defaultPrice: 30000 },
    { nameFr: "Câble USB-C", nameWolof: "Kaabl USB-C", category: "energieTech", unit: "unité", defaultPrice: 40000 },
    { nameFr: "Écouteurs filaires", nameWolof: "Ekutërs", category: "energieTech", unit: "unité", defaultPrice: 30000 },
    { nameFr: "Écouteurs Bluetooth", nameWolof: "Ekutërs Bluetooth", category: "energieTech", unit: "unité", defaultPrice: 150000 },
    { nameFr: "Carte de recharge Orange 1000F", nameWolof: "Kart Oraas", category: "energieTech", unit: "unité", defaultPrice: 100000 },
    { nameFr: "Carte de recharge Orange 2000F", nameWolof: "Kart Oraas 2000", category: "energieTech", unit: "unité", defaultPrice: 200000 },
    { nameFr: "Carte de recharge Orange 5000F", nameWolof: "Kart Oraas 5000", category: "energieTech", unit: "unité", defaultPrice: 500000 },
    { nameFr: "Carte de recharge Free 1000F", nameWolof: "Kart Free", category: "energieTech", unit: "unité", defaultPrice: 100000 },
    { nameFr: "Carte de recharge Free 2000F", nameWolof: "Kart Free 2000", category: "energieTech", unit: "unité", defaultPrice: 200000 },
    { nameFr: "Carte de recharge Expresso 1000F", nameWolof: "Kart Ekspreso", category: "energieTech", unit: "unité", defaultPrice: 100000 },
    { nameFr: "Lampe torche LED", nameWolof: "Laamp tors", category: "energieTech", unit: "unité", defaultPrice: 30000 },
    { nameFr: "Lampe solaire rechargeable", nameWolof: "Laamp soler", category: "energieTech", unit: "unité", defaultPrice: 150000 },
    { nameFr: "Panneau solaire portable", nameWolof: "Pano soler", category: "energieTech", unit: "unité", defaultPrice: 500000 },
    { nameFr: "Batterie externe 10000mAh", nameWolof: "Bateri ekstërn", category: "energieTech", unit: "unité", defaultPrice: 200000 },
    { nameFr: "Multiprise électrique", nameWolof: "Multipriis", category: "energieTech", unit: "unité", defaultPrice: 50000 },
    { nameFr: "Rallonge électrique 5m", nameWolof: "Raloŋj", category: "energieTech", unit: "unité", defaultPrice: 60000 },
    { nameFr: "Ventilateur de table", nameWolof: "Waŋtilatëer tabl", category: "energieTech", unit: "unité", defaultPrice: 400000 },
    { nameFr: "Ventilateur sur pied", nameWolof: "Waŋtilatëer tëdd", category: "energieTech", unit: "unité", defaultPrice: 600000 },
    { nameFr: "Fer à repasser", nameWolof: "Fer repase", category: "energieTech", unit: "unité", defaultPrice: 400000 },
    { nameFr: "Radio FM portable", nameWolof: "Rajo", category: "energieTech", unit: "unité", defaultPrice: 150000 },
    { nameFr: "Clé USB 16Go", nameWolof: "Kle USB", category: "energieTech", unit: "unité", defaultPrice: 60000 },
    { nameFr: "Clé USB 32Go", nameWolof: "Kle USB 32", category: "energieTech", unit: "unité", defaultPrice: 80000 },
    { nameFr: "Carte mémoire 32Go", nameWolof: "Kart memwaar", category: "energieTech", unit: "unité", defaultPrice: 60000 },
    { nameFr: "Adaptateur prise", nameWolof: "Adaptatëer", category: "energieTech", unit: "unité", defaultPrice: 20000 },
    { nameFr: "Interrupteur électrique", nameWolof: "Eŋteruptëer", category: "energieTech", unit: "unité", defaultPrice: 15000 },
    { nameFr: "Prise murale", nameWolof: "Priis miir", category: "energieTech", unit: "unité", defaultPrice: 15000 },
    { nameFr: "Fil électrique 1.5mm (mètre)", nameWolof: "Fil elektrik", category: "energieTech", unit: "mètre", defaultPrice: 10000 },
    { nameFr: "Groupe électrogène portable", nameWolof: "Grup elektrojeen", category: "energieTech", unit: "unité", defaultPrice: 10000000 },

    // ═══════════════════════════════════════════
    // QUINCAILLERIE (35 articles)
    // ═══════════════════════════════════════════
    { nameFr: "Ciment CEM II 50kg", nameWolof: "Simaan", category: "quincaillerie", unit: "sac", defaultPrice: 450000 },
    { nameFr: "Fer à béton 8mm (barre 12m)", nameWolof: "Fer betoŋ 8", category: "quincaillerie", unit: "barre", defaultPrice: 300000 },
    { nameFr: "Fer à béton 10mm (barre 12m)", nameWolof: "Fer betoŋ 10", category: "quincaillerie", unit: "barre", defaultPrice: 450000 },
    { nameFr: "Fer à béton 12mm (barre 12m)", nameWolof: "Fer betoŋ 12", category: "quincaillerie", unit: "barre", defaultPrice: 600000 },
    { nameFr: "Peinture vinylique 4L", nameWolof: "Pëntir", category: "quincaillerie", unit: "seau", defaultPrice: 500000 },
    { nameFr: "Peinture glycéro 4L", nameWolof: "Pëntir glisero", category: "quincaillerie", unit: "seau", defaultPrice: 600000 },
    { nameFr: "Peinture laquée 1L", nameWolof: "Pëntir lake", category: "quincaillerie", unit: "pot", defaultPrice: 200000 },
    { nameFr: "Pinceau plat 5cm", nameWolof: "Pënso", category: "quincaillerie", unit: "unité", defaultPrice: 15000 },
    { nameFr: "Rouleau à peinture", nameWolof: "Rulo pëntir", category: "quincaillerie", unit: "unité", defaultPrice: 25000 },
    { nameFr: "Vis à bois (boîte 100)", nameWolof: "Wiis", category: "quincaillerie", unit: "boîte", defaultPrice: 30000 },
    { nameFr: "Clous 5cm (kg)", nameWolof: "Kaawal", category: "quincaillerie", unit: "kg", defaultPrice: 30000 },
    { nameFr: "Clous 8cm (kg)", nameWolof: "Kaawal bu mag", category: "quincaillerie", unit: "kg", defaultPrice: 35000 },
    { nameFr: "Serrure de porte", nameWolof: "Kadënas bunt", category: "quincaillerie", unit: "unité", defaultPrice: 200000 },
    { nameFr: "Cadenas 40mm", nameWolof: "Kadënas", category: "quincaillerie", unit: "unité", defaultPrice: 50000 },
    { nameFr: "Cadenas 60mm", nameWolof: "Kadënas bu mag", category: "quincaillerie", unit: "unité", defaultPrice: 80000 },
    { nameFr: "Tuyau PVC 50mm (4m)", nameWolof: "Tiyo PVC", category: "quincaillerie", unit: "barre", defaultPrice: 150000 },
    { nameFr: "Tuyau PVC 100mm (4m)", nameWolof: "Tiyo PVC bu mag", category: "quincaillerie", unit: "barre", defaultPrice: 250000 },
    { nameFr: "Coude PVC 50mm", nameWolof: "Kud PVC", category: "quincaillerie", unit: "unité", defaultPrice: 15000 },
    { nameFr: "Robinet de cuisine", nameWolof: "Robinee", category: "quincaillerie", unit: "unité", defaultPrice: 150000 },
    { nameFr: "Robinet de douche", nameWolof: "Robinee duus", category: "quincaillerie", unit: "unité", defaultPrice: 200000 },
    { nameFr: "Marteau", nameWolof: "Marto", category: "quincaillerie", unit: "unité", defaultPrice: 50000 },
    { nameFr: "Tournevis plat", nameWolof: "Turnëwiis", category: "quincaillerie", unit: "unité", defaultPrice: 20000 },
    { nameFr: "Tournevis cruciforme", nameWolof: "Turnëwiis krisiiform", category: "quincaillerie", unit: "unité", defaultPrice: 20000 },
    { nameFr: "Pince universelle", nameWolof: "Paans", category: "quincaillerie", unit: "unité", defaultPrice: 30000 },
    { nameFr: "Scie à métaux", nameWolof: "Si metoo", category: "quincaillerie", unit: "unité", defaultPrice: 50000 },
    { nameFr: "Mètre ruban 5m", nameWolof: "Meetr ribaŋ", category: "quincaillerie", unit: "unité", defaultPrice: 20000 },
    { nameFr: "Niveau à bulle", nameWolof: "Niwo", category: "quincaillerie", unit: "unité", defaultPrice: 30000 },
    { nameFr: "Brouette", nameWolof: "Burweet", category: "quincaillerie", unit: "unité", defaultPrice: 500000 },
    { nameFr: "Truelle", nameWolof: "Truweel", category: "quincaillerie", unit: "unité", defaultPrice: 20000 },
    { nameFr: "Fil de fer recuit (kg)", nameWolof: "Fil fer", category: "quincaillerie", unit: "kg", defaultPrice: 40000 },
    { nameFr: "Grillage métallique (mètre)", nameWolof: "Griyaas", category: "quincaillerie", unit: "mètre", defaultPrice: 80000 },
    { nameFr: "Charnière de porte", nameWolof: "Sarniyeer", category: "quincaillerie", unit: "paire", defaultPrice: 20000 },
    { nameFr: "Poignée de porte", nameWolof: "Puañee bunt", category: "quincaillerie", unit: "unité", defaultPrice: 40000 },
    { nameFr: "Scie égoïne", nameWolof: "Si bant", category: "quincaillerie", unit: "unité", defaultPrice: 40000 },
    { nameFr: "Pioche", nameWolof: "Piyoos", category: "quincaillerie", unit: "unité", defaultPrice: 60000 },

    // ═══════════════════════════════════════════
    // USTENSILES DE CUISINE (35 articles)
    // ═══════════════════════════════════════════
    { nameFr: "Casserole aluminium grande", nameWolof: "Kasërol bu mag", category: "ustensilesCuisine", unit: "unité", defaultPrice: 200000 },
    { nameFr: "Casserole aluminium moyenne", nameWolof: "Kasërol bu yëg", category: "ustensilesCuisine", unit: "unité", defaultPrice: 150000 },
    { nameFr: "Casserole aluminium petite", nameWolof: "Kasërol bu ndaw", category: "ustensilesCuisine", unit: "unité", defaultPrice: 100000 },
    { nameFr: "Marmite fonte grande", nameWolof: "Cërëg bu mag", category: "ustensilesCuisine", unit: "unité", defaultPrice: 400000 },
    { nameFr: "Poêle antiadhésive 26cm", nameWolof: "Puwaal", category: "ustensilesCuisine", unit: "unité", defaultPrice: 150000 },
    { nameFr: "Poêle antiadhésive 30cm", nameWolof: "Puwaal bu mag", category: "ustensilesCuisine", unit: "unité", defaultPrice: 200000 },
    { nameFr: "Wok 32cm", nameWolof: "Wok", category: "ustensilesCuisine", unit: "unité", defaultPrice: 180000 },
    { nameFr: "Couteau de cuisine", nameWolof: "Paaka kizin", category: "ustensilesCuisine", unit: "unité", defaultPrice: 30000 },
    { nameFr: "Couteau à pain", nameWolof: "Paaka mburu", category: "ustensilesCuisine", unit: "unité", defaultPrice: 25000 },
    { nameFr: "Set de couteaux (6)", nameWolof: "Set paaka", category: "ustensilesCuisine", unit: "set", defaultPrice: 150000 },
    { nameFr: "Planche à découper", nameWolof: "Plaŋs dëkupe", category: "ustensilesCuisine", unit: "unité", defaultPrice: 30000 },
    { nameFr: "Louche", nameWolof: "Luus", category: "ustensilesCuisine", unit: "unité", defaultPrice: 15000 },
    { nameFr: "Spatule en bois", nameWolof: "Xaatim bant", category: "ustensilesCuisine", unit: "unité", defaultPrice: 10000 },
    { nameFr: "Écumoire", nameWolof: "Ekimwaar", category: "ustensilesCuisine", unit: "unité", defaultPrice: 15000 },
    { nameFr: "Passoire", nameWolof: "Paswaar", category: "ustensilesCuisine", unit: "unité", defaultPrice: 20000 },
    { nameFr: "Bol en inox (set de 3)", nameWolof: "Bool inoks", category: "ustensilesCuisine", unit: "set", defaultPrice: 50000 },
    { nameFr: "Plat en émail", nameWolof: "Pla emaay", category: "ustensilesCuisine", unit: "unité", defaultPrice: 30000 },
    { nameFr: "Plat rond en plastique", nameWolof: "Pla plastik", category: "ustensilesCuisine", unit: "unité", defaultPrice: 15000 },
    { nameFr: "Verre à thé (lot de 6)", nameWolof: "Weer attaaya", category: "ustensilesCuisine", unit: "lot", defaultPrice: 25000 },
    { nameFr: "Tasse en porcelaine", nameWolof: "Taas", category: "ustensilesCuisine", unit: "unité", defaultPrice: 15000 },
    { nameFr: "Théière en inox", nameWolof: "Berraada", category: "ustensilesCuisine", unit: "unité", defaultPrice: 50000 },
    { nameFr: "Bouilloire électrique", nameWolof: "Buywaar elektrik", category: "ustensilesCuisine", unit: "unité", defaultPrice: 200000 },
    { nameFr: "Thermos 1L", nameWolof: "Termos", category: "ustensilesCuisine", unit: "unité", defaultPrice: 60000 },
    { nameFr: "Réchaud à gaz 1 feu", nameWolof: "Resoo gaas", category: "ustensilesCuisine", unit: "unité", defaultPrice: 100000 },
    { nameFr: "Réchaud à gaz 2 feux", nameWolof: "Resoo gaas 2", category: "ustensilesCuisine", unit: "unité", defaultPrice: 200000 },
    { nameFr: "Foyer amélioré (fourneau)", nameWolof: "Fwaaye", category: "ustensilesCuisine", unit: "unité", defaultPrice: 100000 },
    { nameFr: "Couvert inox (set 24)", nameWolof: "Kuweer", category: "ustensilesCuisine", unit: "set", defaultPrice: 80000 },
    { nameFr: "Assiette plate (lot de 6)", nameWolof: "Asyeet", category: "ustensilesCuisine", unit: "lot", defaultPrice: 60000 },
    { nameFr: "Assiette creuse (lot de 6)", nameWolof: "Asyeet bu xonq", category: "ustensilesCuisine", unit: "lot", defaultPrice: 60000 },
    { nameFr: "Cocotte-minute 6L", nameWolof: "Kokot minit", category: "ustensilesCuisine", unit: "unité", defaultPrice: 500000 },
    { nameFr: "Mortier et pilon", nameWolof: "Lëgën ak taas", category: "ustensilesCuisine", unit: "set", defaultPrice: 40000 },
    { nameFr: "Râpe à légumes", nameWolof: "Raap leyim", category: "ustensilesCuisine", unit: "unité", defaultPrice: 15000 },
    { nameFr: "Ouvre-boîte", nameWolof: "Uwri bwaat", category: "ustensilesCuisine", unit: "unité", defaultPrice: 15000 },
    { nameFr: "Boîte hermétique (set de 3)", nameWolof: "Bwaat plastik", category: "ustensilesCuisine", unit: "set", defaultPrice: 40000 },
    { nameFr: "Moulin à épices", nameWolof: "Mulaŋ epis", category: "ustensilesCuisine", unit: "unité", defaultPrice: 25000 },

    // ═══════════════════════════════════════════
    // MATÉRIAUX DE CONSTRUCTION (35 articles)
    // ═══════════════════════════════════════════
    { nameFr: "Parpaing creux 15x20x40", nameWolof: "Parpeen", category: "materiaux", unit: "unité", defaultPrice: 15000 },
    { nameFr: "Parpaing creux 20x20x40", nameWolof: "Parpeen bu mag", category: "materiaux", unit: "unité", defaultPrice: 20000 },
    { nameFr: "Parpaing plein 15x20x40", nameWolof: "Parpeen pleŋ", category: "materiaux", unit: "unité", defaultPrice: 25000 },
    { nameFr: "Brique en terre cuite", nameWolof: "Brik", category: "materiaux", unit: "unité", defaultPrice: 10000 },
    { nameFr: "Sable fin (m³)", nameWolof: "Suuf", category: "materiaux", unit: "m³", defaultPrice: 1000000 },
    { nameFr: "Gravier (m³)", nameWolof: "Grawiye", category: "materiaux", unit: "m³", defaultPrice: 1200000 },
    { nameFr: "Laterite (m³)", nameWolof: "Laterit", category: "materiaux", unit: "m³", defaultPrice: 600000 },
    { nameFr: "Tôle ondulée (2m)", nameWolof: "Tool", category: "materiaux", unit: "feuille", defaultPrice: 300000 },
    { nameFr: "Tôle ondulée (3m)", nameWolof: "Tool bu gudd", category: "materiaux", unit: "feuille", defaultPrice: 400000 },
    { nameFr: "Carrelage sol 40x40 (m²)", nameWolof: "Karlaas", category: "materiaux", unit: "m²", defaultPrice: 200000 },
    { nameFr: "Carrelage mur 25x40 (m²)", nameWolof: "Karlaas miir", category: "materiaux", unit: "m²", defaultPrice: 180000 },
    { nameFr: "Ciment colle 25kg", nameWolof: "Simaan kol", category: "materiaux", unit: "sac", defaultPrice: 300000 },
    { nameFr: "Joint carrelage 5kg", nameWolof: "Jweŋ karlaas", category: "materiaux", unit: "sac", defaultPrice: 60000 },
    { nameFr: "Bois chevron 6x8 (4m)", nameWolof: "Bant", category: "materiaux", unit: "barre", defaultPrice: 200000 },
    { nameFr: "Bois madrier 5x15 (4m)", nameWolof: "Bant bu mag", category: "materiaux", unit: "barre", defaultPrice: 350000 },
    { nameFr: "Contreplaqué 6mm (2.4x1.2m)", nameWolof: "Kontrëplake", category: "materiaux", unit: "panneau", defaultPrice: 300000 },
    { nameFr: "Contreplaqué 12mm (2.4x1.2m)", nameWolof: "Kontrëplake bu gënn", category: "materiaux", unit: "panneau", defaultPrice: 500000 },
    { nameFr: "Plâtre 25kg", nameWolof: "Plaatr", category: "materiaux", unit: "sac", defaultPrice: 200000 },
    { nameFr: "Enduit mural 25kg", nameWolof: "Aŋdwi", category: "materiaux", unit: "sac", defaultPrice: 250000 },
    { nameFr: "Imperméabilisant 5L", nameWolof: "Eŋpermeyabilizaan", category: "materiaux", unit: "bidon", defaultPrice: 300000 },
    { nameFr: "Porte en bois simple", nameWolof: "Bunt bant", category: "materiaux", unit: "unité", defaultPrice: 800000 },
    { nameFr: "Porte métallique", nameWolof: "Bunt fer", category: "materiaux", unit: "unité", defaultPrice: 1200000 },
    { nameFr: "Fenêtre aluminium (1x1m)", nameWolof: "Palanteer", category: "materiaux", unit: "unité", defaultPrice: 600000 },
    { nameFr: "Fenêtre aluminium (1.5x1.2m)", nameWolof: "Palanteer bu mag", category: "materiaux", unit: "unité", defaultPrice: 900000 },
    { nameFr: "Gouttière PVC (4m)", nameWolof: "Gutiyeer", category: "materiaux", unit: "barre", defaultPrice: 200000 },
    { nameFr: "WC complet avec réservoir", nameWolof: "WC", category: "materiaux", unit: "set", defaultPrice: 1500000 },
    { nameFr: "Lavabo avec robinet", nameWolof: "Lawabo", category: "materiaux", unit: "set", defaultPrice: 800000 },
    { nameFr: "Évier inox", nameWolof: "Ewiye", category: "materiaux", unit: "unité", defaultPrice: 600000 },
    { nameFr: "Câble électrique 2.5mm (100m)", nameWolof: "Kaabl elektrik", category: "materiaux", unit: "rouleau", defaultPrice: 500000 },
    { nameFr: "Tube fluorescent 1.2m", nameWolof: "Tib florësaan", category: "materiaux", unit: "unité", defaultPrice: 40000 },
    { nameFr: "Dalle de sol 30x30", nameWolof: "Dal", category: "materiaux", unit: "m²", defaultPrice: 150000 },
    { nameFr: "Colle carrelage 25kg", nameWolof: "Kol karlaas", category: "materiaux", unit: "sac", defaultPrice: 280000 },
    { nameFr: "Mousse polyuréthane 750ml", nameWolof: "Muus", category: "materiaux", unit: "bouteille", defaultPrice: 80000 },
    { nameFr: "Silicone sanitaire", nameWolof: "Silikoon", category: "materiaux", unit: "tube", defaultPrice: 40000 },
    { nameFr: "Échelle aluminium 3m", nameWolof: "Esel", category: "materiaux", unit: "unité", defaultPrice: 600000 },

    // ═══════════════════════════════════════════
    // MOBILIER (35 articles)
    // ═══════════════════════════════════════════
    { nameFr: "Chaise en plastique", nameWolof: "Siis plastik", category: "mobilier", unit: "unité", defaultPrice: 150000 },
    { nameFr: "Chaise en bois", nameWolof: "Siis bant", category: "mobilier", unit: "unité", defaultPrice: 300000 },
    { nameFr: "Fauteuil en osier", nameWolof: "Fotëy ozye", category: "mobilier", unit: "unité", defaultPrice: 500000 },
    { nameFr: "Tabouret en plastique", nameWolof: "Tabure plastik", category: "mobilier", unit: "unité", defaultPrice: 40000 },
    { nameFr: "Table de cuisine", nameWolof: "Tabl kizin", category: "mobilier", unit: "unité", defaultPrice: 500000 },
    { nameFr: "Table de salon", nameWolof: "Tabl saloŋ", category: "mobilier", unit: "unité", defaultPrice: 800000 },
    { nameFr: "Table basse", nameWolof: "Tabl baas", category: "mobilier", unit: "unité", defaultPrice: 400000 },
    { nameFr: "Bureau simple", nameWolof: "Biro", category: "mobilier", unit: "unité", defaultPrice: 600000 },
    { nameFr: "Armoire 2 portes", nameWolof: "Armwaar", category: "mobilier", unit: "unité", defaultPrice: 1200000 },
    { nameFr: "Armoire 3 portes", nameWolof: "Armwaar bu mag", category: "mobilier", unit: "unité", defaultPrice: 1800000 },
    { nameFr: "Étagère en bois 5 niveaux", nameWolof: "Etajeer bant", category: "mobilier", unit: "unité", defaultPrice: 400000 },
    { nameFr: "Étagère métallique", nameWolof: "Etajeer fer", category: "mobilier", unit: "unité", defaultPrice: 300000 },
    { nameFr: "Lit simple en bois", nameWolof: "Laal bant", category: "mobilier", unit: "unité", defaultPrice: 800000 },
    { nameFr: "Lit double en bois", nameWolof: "Laal bu mag", category: "mobilier", unit: "unité", defaultPrice: 1200000 },
    { nameFr: "Lit superposé", nameWolof: "Laal superpoze", category: "mobilier", unit: "unité", defaultPrice: 1500000 },
    { nameFr: "Matelas mousse simple", nameWolof: "Matla", category: "mobilier", unit: "unité", defaultPrice: 500000 },
    { nameFr: "Matelas mousse double", nameWolof: "Matla bu mag", category: "mobilier", unit: "unité", defaultPrice: 800000 },
    { nameFr: "Matelas à ressorts simple", nameWolof: "Matla resoor", category: "mobilier", unit: "unité", defaultPrice: 1000000 },
    { nameFr: "Oreiller", nameWolof: "Kusaan", category: "mobilier", unit: "unité", defaultPrice: 60000 },
    { nameFr: "Drap housse", nameWolof: "Dra", category: "mobilier", unit: "unité", defaultPrice: 80000 },
    { nameFr: "Couverture polaire", nameWolof: "Kuyertir", category: "mobilier", unit: "unité", defaultPrice: 100000 },
    { nameFr: "Natte en plastique tressé", nameWolof: "Taal plastik", category: "mobilier", unit: "unité", defaultPrice: 60000 },
    { nameFr: "Tapis de salon", nameWolof: "Tapi saloŋ", category: "mobilier", unit: "unité", defaultPrice: 300000 },
    { nameFr: "Rideau (paire)", nameWolof: "Rido", category: "mobilier", unit: "paire", defaultPrice: 100000 },
    { nameFr: "Miroir mural", nameWolof: "Seetu miir", category: "mobilier", unit: "unité", defaultPrice: 150000 },
    { nameFr: "Cadre photo", nameWolof: "Kadr foto", category: "mobilier", unit: "unité", defaultPrice: 30000 },
    { nameFr: "Horloge murale", nameWolof: "Montar miir", category: "mobilier", unit: "unité", defaultPrice: 60000 },
    { nameFr: "Parasol de marché", nameWolof: "Parasol", category: "mobilier", unit: "unité", defaultPrice: 200000 },
    { nameFr: "Banc en bois (3 places)", nameWolof: "Baŋ bant", category: "mobilier", unit: "unité", defaultPrice: 400000 },
    { nameFr: "Salon 7 places (set)", nameWolof: "Saloŋ set", category: "mobilier", unit: "set", defaultPrice: 5000000 },
    { nameFr: "Bibliothèque en bois", nameWolof: "Bibliotek", category: "mobilier", unit: "unité", defaultPrice: 600000 },
    { nameFr: "Commode 4 tiroirs", nameWolof: "Komod", category: "mobilier", unit: "unité", defaultPrice: 500000 },
    { nameFr: "Coffre de rangement", nameWolof: "Kofr", category: "mobilier", unit: "unité", defaultPrice: 300000 },
    { nameFr: "Chaise longue pliante", nameWolof: "Siis gudd", category: "mobilier", unit: "unité", defaultPrice: 150000 },
    { nameFr: "Moustiquaire lit double", nameWolof: "Mustikeer", category: "mobilier", unit: "unité", defaultPrice: 100000 },
  ];

  console.log(`📦 Inserting ${products.length} products...`);

  for (const product of products) {
    await prisma.defaultProduct.create({ data: product });
  }

  console.log(`✅ ${products.length} products seeded`);

  // Create demo clients for the vendor
  if (vendorUser.vendorProfile) {
    const demoClients = [
      { vendorId: vendorUser.vendorProfile.id, name: "Fallou Ndiaye", phone: "+221770001111", preferredLanguage: "wo" },
      { vendorId: vendorUser.vendorProfile.id, name: "Aminata Diop", phone: "+221770002222", preferredLanguage: "fr" },
      { vendorId: vendorUser.vendorProfile.id, name: "Moussa Ba", phone: "+221770003333", preferredLanguage: "fr" },
      { vendorId: vendorUser.vendorProfile.id, name: "Fatou Sow", phone: "+221770004444", preferredLanguage: "wo" },
      { vendorId: vendorUser.vendorProfile.id, name: "Ibrahim Diallo", phone: "+221770005555", preferredLanguage: "ar" },
    ];

    for (const client of demoClients) {
      await prisma.client.upsert({
        where: { vendorId_phone: { vendorId: client.vendorId, phone: client.phone } },
        update: {},
        create: client,
      });
    }
    console.log("✅ Demo clients created");
  }

  console.log("🎉 Seeding complete!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
